[tool.poetry]
name = "hpc_lecture"
version = "0.1.0"
description = ""
authors = ["astellon <22632787+astellon@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
jupyter = "^1.0.0"
sympy = "^1.6"
matplotlib = "^3.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
